### ISSUE TITLE
[Bug]Doesn't work anymore

### ISSUE THREAD

**Issue by Postfrosch02** [AlexVerrico/octoprint-stats#39]
Doesn't work anymore

Since I updated to the latest version of Octoprint (1.9.1) printerstats doesn't work anymore.

I have already reinstalled the plugin several times, unfortunately without success.

![image](https://github.com/AlexVerrico/octoprint-stats/assets/19331838/c2f18cfc-f53f-4a25-aaca-953075329b84)

![image](https://github.com/AlexVerrico/octoprint-stats/assets/19331838/834e9c58-4625-4a36-ab8c-e032b1266db7)

**Comment by jneilliii** [comment]
I'm getting this error in OctoPrint 1.9.1, OctoPi 1.0.0, Python 3.9.2

```
2023-07-30 11:14:10,522 - octoprint.server.api - ERROR - Error calling SimpleApiPlugin stats
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/api/__init__.py", line 95, in pluginData
    response = api_plugin.on_api_get(request)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_stats/__init__.py", line 301, in on_api_get
    self.refreshWatts(filter_param=self.current_filter)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_stats/__init__.py", line 656, in refreshWatts
    print_df_sum = print_df.groupby("event_ymd")["kwh", "ptime"].sum()
  File "/home/pi/oprint/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 1767, in __getitem__
    raise ValueError(
ValueError: Cannot subset columns with a tuple with more than one element. Use a list instead.
```

**Comment by jneilliii** [comment]
I've submitted the above PR to resolve this issue, which appears to be a deprecation of a technique in pandas >=2.0.0. You can test by copying/pasting the URL below into plugin manager > get more > ...from URL and clicking install.

```
https://github.com/jneilliii/octoprint-stats/archive/refs/heads/master.zip
```

**Comment by Postfrosch02** [comment]
it works again, thanks for the solution 👍
