### ISSUE TITLE
[Bug] install suceeds bit not showing on front end

### ISSUE THREAD

**Issue by CubenetWebHosting** [AlexVerrico/octoprint-stats#41]
**Describe the bug**
Octoprint-stats used to work. I am not sure when it disappeared, unfortunately. I upgraded to the latest Octoprint by creating a backup thereafter creating a new Octoprint instance and restoring the backup.

And then later noticed the Stats are not there any more.

I tried uninstalling and reinstalling the plugin 
pip Can see the plugin but it is not even listed in the plugin manger in Octoprint

I am not sure if it can be reproduced on other systems.

**To Reproduce**
1. Go to Octoprint install octoprint-stats restart
2. octoprint-stats  is not on the front end when refreshing the page

**Expected behavior**

**Screenshots**

**Environment information:**
 - OctoPrint version : 1.9.3
 - OctoPi version    : 1.0.0
browser.user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0
connectivity.connection_check: 1.1.1.1:53
connectivity.connection_ok: True
connectivity.enabled: True
connectivity.online: True
connectivity.resolution_ok: True
env.hardware.cores: 4
env.hardware.freq: 1400.0
env.hardware.ram: 912703488
env.os.bits: 32
env.os.id: linux
env.os.platform: linux
env.plugins.pi_support.model: Raspberry Pi 3 Model B Plus Rev 1.3
env.plugins.pi_support.octopi_camera_stack: webcamd
env.plugins.pi_support.octopi_version: 1.0.0
env.plugins.pi_support.octopiuptodate_build: 1.0.0-1.9.3-20231009151442
env.plugins.pi_support.octopiuptodate_build_short: 2023.10.09.151442
env.plugins.pi_support.throttle_check_enabled: True
env.plugins.pi_support.throttle_check_functional: True
env.plugins.pi_support.throttle_state: 0x80000
env.python.pip: 23.3.1
env.python.version: 3.9.2
env.python.virtualenv: True
octoprint.last_safe_mode.date: unknown
octoprint.last_safe_mode.reason: unknown
octoprint.safe_mode: False
octoprint.version: 1.9.3
systeminfo.generated: 2023-11-14T05:44:41Z
systeminfo.generator: zipapi

**Additional context**
```
Add any other context about the problem here.
2023-11-14 07:31:46,793 - octoprint.plugin.core - ERROR - Error loading plugin stats
Traceback (most recent call last):
  File "/home/johan/oprint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 1294, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/johan/oprint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 52, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/johan/oprint/lib/python3.9/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
  File "/home/johan/oprint/lib/python3.9/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/johan/oprint/lib/python3.9/site-packages/octoprint_stats/__init__.py", line 18, in <module>
    import pandas as pd
  File "/home/johan/oprint/lib/python3.9/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

The install log

```
`~/oprint/bin/pip install https://github.com/AlexVerrico/octoprint-stats/archive/master.zip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/AlexVerrico/octoprint-stats/archive/master.zip
  Using cached https://github.com/AlexVerrico/octoprint-stats/archive/master.zip
  Preparing metadata (setup.py) ... done
Requirement already satisfied: OctoPrint in ./oprint/lib/python3.9/site-packages (from OctoPrint-Stats==3.1.4) (1.9.3)
Requirement already satisfied: tinydb in ./oprint/lib/python3.9/site-packages (from OctoPrint-Stats==3.1.4) (4.8.0)
Requirement already satisfied: pandas in ./oprint/lib/python3.9/site-packages (from OctoPrint-Stats==3.1.4) (2.1.1)
Requirement already satisfied: numpy in ./oprint/lib/python3.9/site-packages (from OctoPrint-Stats==3.1.4) (1.26.0)
Requirement already satisfied: OctoPrint-FileCheck>=2021.2.23 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2021.2.23)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2021.10.11 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2021.10.11)
Requirement already satisfied: OctoPrint-PiSupport>=2023.5.24 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2023.10.10)
Requirement already satisfied: argon2-cffi<22,>=21.3.0 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (21.3.0)
Requirement already satisfied: Babel<2.13,>=2.12.1 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2.12.1)
Requirement already satisfied: cachelib<0.11,>=0.10.2 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (0.10.2)
Requirement already satisfied: Click<9,>=8.1.3 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (8.1.3)
Requirement already satisfied: colorlog<7,>=6.7.0 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (6.7.0)
Requirement already satisfied: emoji<3,>=2.2.0 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2.8.0)
Requirement already satisfied: feedparser<7,>=6.0.10 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (6.0.10)
Requirement already satisfied: filetype<2,>=1.2.0 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (1.2.0)
Requirement already satisfied: Flask-Assets<3,>=2.0 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2.0)
Requirement already satisfied: Flask-Babel<4,>=3.1.0 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (3.1.0)
Requirement already satisfied: Flask-Login<0.7,>=0.6.2 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (0.6.2)
Requirement already satisfied: Flask-Limiter<4,>=3.3.0 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (3.5.0)
Requirement already satisfied: flask<2.3,>=2.2.3 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2.2.5)
Requirement already satisfied: frozendict<3,>=2.3.7 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2.3.8)
Requirement already satisfied: future<1,>=0.18.3 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (0.18.3)
Requirement already satisfied: markdown<4,>=3.4.3 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (3.5)
Requirement already satisfied: netaddr<0.9,>=0.8 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (0.8.0)
Requirement already satisfied: netifaces<1,>=0.11 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (0.11.0)
Requirement already satisfied: passlib<2,>=1.7.4 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (1.7.4)
Requirement already satisfied: pathvalidate<3,>=2.5.2 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2.5.2)
Requirement already satisfied: pkginfo<2,>=1.9.6 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (1.9.6)
Requirement already satisfied: psutil<6,>=5.9.4 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (5.9.5)
Requirement already satisfied: pydantic==1.10.12 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (1.10.12)
Requirement already satisfied: pylru<2,>=1.2.1 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (1.2.1)
Requirement already satisfied: pyserial<4,>=3.5 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (3.5)
Requirement already satisfied: PyYAML<7,>=6.0.1 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (6.0.1)
Requirement already satisfied: requests<3,>=2.28.2 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2.31.0)
Requirement already satisfied: sarge==0.1.7.post1 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (0.1.7.post1)
Requirement already satisfied: semantic-version<3,>=2.10.0 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2.10.0)
Requirement already satisfied: sentry-sdk<2,>=1.19.1 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (1.31.0)
Requirement already satisfied: tornado<7,>=6.2 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (6.2)
Requirement already satisfied: watchdog<3,>=2.3.1 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2.3.1)
Requirement already satisfied: websocket-client<2,>=1.5.1 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (1.6.4)
Requirement already satisfied: werkzeug<2.3,>=2.2.3 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2.2.3)
Requirement already satisfied: wrapt<1.16,>=1.15 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (1.15.0)
Requirement already satisfied: zeroconf==0.39.4 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (0.39.4)
Requirement already satisfied: zipstream-ng<2.0.0,>=1.5.0 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (1.7.1)
Requirement already satisfied: blinker<2,>=1.6.1 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (1.6.3)
Requirement already satisfied: class-doc<0.3,>=0.2.6 in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (0.2.6)
Requirement already satisfied: regex in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (2022.9.13)
Requirement already satisfied: unidecode in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (0.4.21)
Requirement already satisfied: wheel in ./oprint/lib/python3.9/site-packages (from OctoPrint->OctoPrint-Stats==3.1.4) (0.41.3)
Requirement already satisfied: typing-extensions>=4.2.0 in ./oprint/lib/python3.9/site-packages (from pydantic==1.10.12->OctoPrint->OctoPrint-Stats==3.1.4) (4.4.0)
Requirement already satisfied: async-timeout>=4.0.1 in ./oprint/lib/python3.9/site-packages (from zeroconf==0.39.4->OctoPrint->OctoPrint-Stats==3.1.4) (4.0.3)
Requirement already satisfied: ifaddr>=0.1.7 in ./oprint/lib/python3.9/site-packages (from zeroconf==0.39.4->OctoPrint->OctoPrint-Stats==3.1.4) (0.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./oprint/lib/python3.9/site-packages (from pandas->OctoPrint-Stats==3.1.4) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./oprint/lib/python3.9/site-packages (from pandas->OctoPrint-Stats==3.1.4) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in ./oprint/lib/python3.9/site-packages (from pandas->OctoPrint-Stats==3.1.4) (2023.3)
Requirement already satisfied: argon2-cffi-bindings in ./oprint/lib/python3.9/site-packages (from argon2-cffi<22,>=21.3.0->OctoPrint->OctoPrint-Stats==3.1.4) (21.2.0)
Requirement already satisfied: more-itertools>=5.0.0 in ./oprint/lib/python3.9/site-packages (from class-doc<0.3,>=0.2.6->OctoPrint->OctoPrint-Stats==3.1.4) (10.1.0)
Requirement already satisfied: sgmllib3k in ./oprint/lib/python3.9/site-packages (from feedparser<7,>=6.0.10->OctoPrint->OctoPrint-Stats==3.1.4) (1.0.0)
Requirement already satisfied: Jinja2>=3.0 in ./oprint/lib/python3.9/site-packages (from flask<2.3,>=2.2.3->OctoPrint->OctoPrint-Stats==3.1.4) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in ./oprint/lib/python3.9/site-packages (from flask<2.3,>=2.2.3->OctoPrint->OctoPrint-Stats==3.1.4) (2.1.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in ./oprint/lib/python3.9/site-packages (from flask<2.3,>=2.2.3->OctoPrint->OctoPrint-Stats==3.1.4) (5.0.0)
Requirement already satisfied: webassets>=2.0 in ./oprint/lib/python3.9/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->OctoPrint-Stats==3.1.4) (2.0)
Requirement already satisfied: limits>=2.8 in ./oprint/lib/python3.9/site-packages (from Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-Stats==3.1.4) (3.6.0)
Requirement already satisfied: ordered-set<5,>4 in ./oprint/lib/python3.9/site-packages (from Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-Stats==3.1.4) (4.1.0)
Requirement already satisfied: rich<14,>=12 in ./oprint/lib/python3.9/site-packages (from Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-Stats==3.1.4) (12.6.0)
Requirement already satisfied: six>=1.5 in ./oprint/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->OctoPrint-Stats==3.1.4) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./oprint/lib/python3.9/site-packages (from requests<3,>=2.28.2->OctoPrint->OctoPrint-Stats==3.1.4) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in ./oprint/lib/python3.9/site-packages (from requests<3,>=2.28.2->OctoPrint->OctoPrint-Stats==3.1.4) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./oprint/lib/python3.9/site-packages (from requests<3,>=2.28.2->OctoPrint->OctoPrint-Stats==3.1.4) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in ./oprint/lib/python3.9/site-packages (from requests<3,>=2.28.2->OctoPrint->OctoPrint-Stats==3.1.4) (2022.9.24)
Requirement already satisfied: MarkupSafe>=2.1.1 in ./oprint/lib/python3.9/site-packages (from werkzeug<2.3,>=2.2.3->OctoPrint->OctoPrint-Stats==3.1.4) (2.1.1)
Requirement already satisfied: zipp>=0.5 in ./oprint/lib/python3.9/site-packages (from importlib-metadata>=3.6.0->flask<2.3,>=2.2.3->OctoPrint->OctoPrint-Stats==3.1.4) (3.10.0)
Requirement already satisfied: deprecated>=1.2 in ./oprint/lib/python3.9/site-packages (from limits>=2.8->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-Stats==3.1.4) (1.2.13)
Requirement already satisfied: importlib-resources>=1.3 in ./oprint/lib/python3.9/site-packages (from limits>=2.8->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-Stats==3.1.4) (6.1.0)
Requirement already satisfied: packaging<24,>=21 in ./oprint/lib/python3.9/site-packages (from limits>=2.8->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-Stats==3.1.4) (21.3)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in ./oprint/lib/python3.9/site-packages (from rich<14,>=12->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-Stats==3.1.4) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in ./oprint/lib/python3.9/site-packages (from rich<14,>=12->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-Stats==3.1.4) (2.13.0)
Requirement already satisfied: cffi>=1.0.1 in ./oprint/lib/python3.9/site-packages (from argon2-cffi-bindings->argon2-cffi<22,>=21.3.0->OctoPrint->OctoPrint-Stats==3.1.4) (1.15.1)
Requirement already satisfied: pycparser in ./oprint/lib/python3.9/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi<22,>=21.3.0->OctoPrint->OctoPrint-Stats==3.1.4) (2.21)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./oprint/lib/python3.9/site-packages (from packaging<24,>=21->limits>=2.8->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-Stats==3.1.4) (3.0.9)
Building wheels for collected packages: OctoPrint-Stats
  Building wheel for OctoPrint-Stats (setup.py) ... done
  Created wheel for OctoPrint-Stats: filename=OctoPrint_Stats-3.1.4-py3-none-any.whl size=870606 sha256=6346ac443b86d52e58888ab40d70eb0e9db5369b8cf6bb119c1e2ada160337ca
  Stored in directory: /tmp/pip-ephem-wheel-cache-fwtyhkdx/wheels/38/26/d4/7d6f53061105f3e009e62004f9900468d7e01c3af70eb65965
Successfully built OctoPrint-Stats
Installing collected packages: OctoPrint-Stats
Successfully installed OctoPrint-Stats-3.1.4`
```

**Comment by marcbres** [comment]
I'm here to report that I am facing the same error, so CubenetWebHosting is not alone on this. I've been trying to reinstall/update pandas and numpy packages with pip, but have not been lucky to get this working

**Comment by jacopotediosi** [comment]
`sudo apt-get install libopenblas-dev` solved for me

**Comment by marcbres** [comment]
Thank you @jacopotediosi, I am wondering now how did you get to that package. Anyways with this package the problem is solved.
