### ISSUE TITLE
[Bug] Plugin won't install

### ISSUE THREAD

**Issue by TheAussieTinker** [AlexVerrico/octoprint-stats#43]
**Describe the bug**
I have octoprint setup on a raspberry pi and I have tried a few times to install the printer statistics plugin through the plugin manager and when octoprint restarts nothing appears

**Environment information:**
 - Octoprint Version: 1.10.1
 - Browser: Brave
 - Python Version: 3.9.2
 - Operating system that Octoprint is running on: OctoPi 1.0.0 (build 2024.05.14.100113)

**Comment by Ariosinm** [comment]
Hi, I have further info about this issue, this looks like a bad importing of pandas in line 18


>   File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_stats/__init__.py", line 18, in <module>
>     import pandas as pd
>   File "/home/pi/oprint/lib/python3.9/site-packages/pandas/__init__.py", line 19, in <module>
>     raise ImportError(
> ImportError: Unable to import required dependencies:
> numpy: Error importing numpy: you should not try to import numpy from
>         its source directory; please exit the numpy source tree, and relaunch
>         your python interpreter from there.
> 2024-09-03 10:33:56,247 - octoprint.plugin.core - ERROR - Error loading plugin stats
> Traceback (most recent call last):
>   File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 1297, in _import_plugin
>     module = _load_module(module_name, spec)
>   File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 52, in _load_module
>     return imp.load_module(name, f, filename, details)
>   File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/vendor/imp.py", line 238, in load_module
>     return load_package(name, filename)
>   File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/vendor/imp.py", line 212, in load_package
>     return _load(spec)
>   File "<frozen importlib._bootstrap>", line 711, in _load
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
_>   **File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_stats/__init__.py", line 18, in <module>**
>     **import pandas as pd**_
>   File "/home/pi/oprint/lib/python3.9/site-packages/pandas/__init__.py", line 19, in <module>
>     raise ImportError(
> ImportError: Unable to import required dependencies:
> numpy: Error importing numpy: you should not try to import numpy from
>         its source directory; please exit the numpy source tree, and relaunch
>         your python interpreter from there.

**Comment by moya8352** [comment]
Thanks for this answer... but what can we do now ? 
The plugin will be corrected ?

**Comment by projectandmakeit** [comment]
Hi, I was facing te same issue, looking at the log, there was a missing library in OctoPi, the plugin was succesfully installed but fails on initialization.
Solved installing:
sudo apt install libopenblas-dev

Cheers

**Comment by moya8352** [comment]
OK... and can u please tell how we can install sudo apt install libopenblas-dev ? :)
I am not the best for it.

**Comment by projectandmakeit** [comment]
> OK... and can u please tell how we can install sudo apt install libopenblas-dev ? :) I am not the best for it.

in a terminal copy and paste:
`sudo apt install libopenblas-dev`
and confirm installation.
